## Tut7 Variable Length Sequences with dynamic_rnn
- http://www.wildml.com/2016/08/rnns-in-tensorflow-a-practical-guide-and-undocumented-features/
- https://github.com/dennybritz/tf-rnn/blob/master/dynamic_rnn.ipynb

In [2]:
import tensorflow as tf
import numpy as np

Modified it to emphasize the dimensions:
- 3 batches
- sequence lenghts: [5, 3, 2]
- 8 features per single time slot ??
- 14 num_units

In [28]:
tf.reset_default_graph()

# Create input data
X = np.random.randn(3, 5, 8)

# The second example is of length 3
X[1,3:] = 0
X[2,2:] = 0
X_lengths = [5, 3, 2]

cell = tf.nn.rnn_cell.LSTMCell(num_units=14, state_is_tuple=True)

outputs, last_states = tf.nn.dynamic_rnn(
    cell=cell,
    dtype=tf.float64,
    sequence_length=X_lengths,
    inputs=X)

result = tf.contrib.learn.run_n(
    {"outputs": outputs, "last_states": last_states},
    n=1,
    feed_dict=None)

assert result[0]["outputs"].shape == (3, 5, 14)
print(result[0]["outputs"])

# Outputs for the second example past past length 3 should be 0
assert (result[0]["outputs"][1,3,:] == np.zeros(cell.output_size)).all()

[[[  2.05174460e-01  -1.06444243e-01  -1.37051566e-01  -1.07263797e-01
     3.06072804e-03   1.44190778e-01  -1.41155068e-01   5.18591427e-05
     1.44045912e-03   2.33687773e-02  -7.72643893e-03   4.36991431e-02
    -7.69519791e-02  -8.05396617e-02]
  [ -1.23545472e-02  -2.40175048e-01  -2.18289577e-01  -1.67445625e-03
     1.83863336e-01   1.71180933e-01  -9.11216879e-02   8.59754425e-03
    -8.15608670e-02   7.12704675e-02   6.17234317e-03  -1.83043565e-03
     3.16399526e-03   1.60634060e-02]
  [ -7.76776489e-02   2.39141433e-02   4.22062987e-02   2.30319081e-02
     1.09984393e-01  -4.45934987e-02  -2.68455761e-02   4.67366440e-02
     9.72062542e-03  -2.95246373e-03   2.42063671e-02  -9.62373897e-02
     7.19976625e-02   7.94916118e-02]
  [ -3.75127323e-02   9.33299049e-02  -8.81036090e-02   6.73511905e-02
     8.81622909e-03   2.06579930e-01   7.05655032e-02  -1.07808747e-02
     5.70471202e-02   8.13228354e-02   6.29085431e-03  -2.13014517e-01
     1.18389698e-01   1.86830059e-

In [29]:
len(result)
print(result[0].keys())
print(result[0]['outputs'].shape)
result[0]['outputs']

dict_keys(['outputs', 'last_states'])
(3, 5, 14)


array([[[  2.05174460e-01,  -1.06444243e-01,  -1.37051566e-01,
          -1.07263797e-01,   3.06072804e-03,   1.44190778e-01,
          -1.41155068e-01,   5.18591427e-05,   1.44045912e-03,
           2.33687773e-02,  -7.72643893e-03,   4.36991431e-02,
          -7.69519791e-02,  -8.05396617e-02],
        [ -1.23545472e-02,  -2.40175048e-01,  -2.18289577e-01,
          -1.67445625e-03,   1.83863336e-01,   1.71180933e-01,
          -9.11216879e-02,   8.59754425e-03,  -8.15608670e-02,
           7.12704675e-02,   6.17234317e-03,  -1.83043565e-03,
           3.16399526e-03,   1.60634060e-02],
        [ -7.76776489e-02,   2.39141433e-02,   4.22062987e-02,
           2.30319081e-02,   1.09984393e-01,  -4.45934987e-02,
          -2.68455761e-02,   4.67366440e-02,   9.72062542e-03,
          -2.95246373e-03,   2.42063671e-02,  -9.62373897e-02,
           7.19976625e-02,   7.94916118e-02],
        [ -3.75127323e-02,   9.33299049e-02,  -8.81036090e-02,
           6.73511905e-02,   8.81622909e-03

In [30]:
result[0]['last_states']

LSTMStateTuple(c=array([[ 0.2832133 ,  0.12365224, -0.30049408, -0.12222228,  0.03061501,
         0.6751284 ,  0.22102632, -0.4301005 ,  0.01114068,  0.12578664,
        -0.03978258, -0.25842269, -0.01870656, -0.12608328],
       [ 0.07874415, -0.30758619, -0.41727271, -0.07243471,  0.05923075,
        -0.13361536,  0.04650936,  0.21136913, -0.09386244,  0.15037781,
         0.10412543, -0.10411921,  0.1817263 , -0.31224965],
       [ 0.34979213,  0.00433126, -0.44031611, -0.11037357,  0.05921797,
        -0.00680248, -0.06215367,  0.0864486 , -0.01179482,  0.09934658,
         0.01557239, -0.18857063,  0.13661763, -0.4238616 ]]), h=array([[ 0.11151555,  0.06006485, -0.08621378, -0.04878057,  0.01279212,
         0.27558161,  0.0743914 , -0.19283017,  0.0043321 ,  0.06560111,
        -0.02019166, -0.07879709, -0.00918261, -0.05032231],
       [ 0.03966138, -0.18166411, -0.16688814, -0.05701733,  0.03307901,
        -0.06606103,  0.02699701,  0.08043214, -0.03891423,  0.07995049,
     

In [33]:
print(result[0]['last_states'].c.shape)
result[0]['last_states'].c

(3, 14)


array([[ 0.2832133 ,  0.12365224, -0.30049408, -0.12222228,  0.03061501,
         0.6751284 ,  0.22102632, -0.4301005 ,  0.01114068,  0.12578664,
        -0.03978258, -0.25842269, -0.01870656, -0.12608328],
       [ 0.07874415, -0.30758619, -0.41727271, -0.07243471,  0.05923075,
        -0.13361536,  0.04650936,  0.21136913, -0.09386244,  0.15037781,
         0.10412543, -0.10411921,  0.1817263 , -0.31224965],
       [ 0.34979213,  0.00433126, -0.44031611, -0.11037357,  0.05921797,
        -0.00680248, -0.06215367,  0.0864486 , -0.01179482,  0.09934658,
         0.01557239, -0.18857063,  0.13661763, -0.4238616 ]])

In [34]:
print(result[0]['last_states'].h.shape)
result[0]['last_states'].h

(3, 14)


array([[ 0.11151555,  0.06006485, -0.08621378, -0.04878057,  0.01279212,
         0.27558161,  0.0743914 , -0.19283017,  0.0043321 ,  0.06560111,
        -0.02019166, -0.07879709, -0.00918261, -0.05032231],
       [ 0.03966138, -0.18166411, -0.16688814, -0.05701733,  0.03307901,
        -0.06606103,  0.02699701,  0.08043214, -0.03891423,  0.07995049,
         0.06514733, -0.06324723,  0.10938745, -0.11378049],
       [ 0.1671844 ,  0.00240612, -0.18749289, -0.06737229,  0.02082075,
        -0.00271987, -0.03796077,  0.04348771, -0.00649385,  0.07049524,
         0.00751144, -0.07686164,  0.04539102, -0.07757196]])