## Tut7 Variable Length Sequences with dynamic_rnn
- http://www.wildml.com/2016/08/rnns-in-tensorflow-a-practical-guide-and-undocumented-features/
- https://github.com/dennybritz/tf-rnn/blob/master/dynamic_rnn.ipynb

In [2]:
import tensorflow as tf
import numpy as np

Modified it to emphasize the dimensions:
- 3 batches
- sequence lenghts: [5, 3, 2]
- 8 features per single time slot ??
- 14 num_units

In [23]:
tf.reset_default_graph()

# Create input data
X = np.random.randn(3, 5, 8)

# The second example is of length 3
X[1,3:] = 0
X[2,2:] = 0
X_lengths = [5, 3, 2]

cell = tf.nn.rnn_cell.LSTMCell(num_units=14, state_is_tuple=True)

outputs, last_states = tf.nn.dynamic_rnn(
    cell=cell,
    dtype=tf.float64,
    sequence_length=X_lengths,
    inputs=X)

result = tf.contrib.learn.run_n(
    {"outputs": outputs, "last_states": last_states},
    n=1,
    feed_dict=None)

assert result[0]["outputs"].shape == (3, 5, 14)
print(result[0]["outputs"])

# Outputs for the second example past past length 3 should be 0
assert (result[0]["outputs"][1,3,:] == np.zeros(cell.output_size)).all()

[[[  4.40746593e-02   1.47605699e-01  -1.75705501e-01  -7.84248790e-03
     1.17614685e-01  -1.22079991e-01   1.47378697e-01   3.27746908e-02
    -7.87004246e-03   1.36408501e-01   3.87147493e-02   6.22202866e-02
    -6.99000380e-05  -6.96840272e-02]
  [ -2.72732768e-01  -1.76299414e-01   1.08405895e-01   2.69031474e-01
    -2.29135868e-02   2.57082238e-02   4.97095622e-02  -2.27653097e-01
    -1.54848154e-01   1.32753905e-01  -3.25897955e-02  -1.21384353e-02
    -1.79045631e-01  -3.54186544e-02]
  [ -6.33221153e-02  -1.65174314e-01  -7.81467971e-02   1.22847882e-01
    -1.27491545e-01  -3.83513492e-02  -1.61563920e-01  -6.61959264e-02
    -5.61699167e-02   3.66758663e-01   1.25203449e-02   7.55569430e-02
     1.05553999e-03  -9.41494830e-03]
  [  4.44139191e-02  -2.34477700e-01  -9.08292091e-02   3.00395910e-02
     5.15902738e-02   2.37161833e-01  -7.89216586e-02   1.57103437e-01
    -1.23670764e-01   4.64051716e-01   8.84066009e-02   2.17937237e-01
     1.18450730e-01   8.77069177e-

In [24]:
len(result)
print(result[0].keys())
print(result[0]['outputs'].shape)
result[0]['outputs']

dict_keys(['outputs', 'last_states'])
(3, 5, 14)


array([[[  4.40746593e-02,   1.47605699e-01,  -1.75705501e-01,
          -7.84248790e-03,   1.17614685e-01,  -1.22079991e-01,
           1.47378697e-01,   3.27746908e-02,  -7.87004246e-03,
           1.36408501e-01,   3.87147493e-02,   6.22202866e-02,
          -6.99000380e-05,  -6.96840272e-02],
        [ -2.72732768e-01,  -1.76299414e-01,   1.08405895e-01,
           2.69031474e-01,  -2.29135868e-02,   2.57082238e-02,
           4.97095622e-02,  -2.27653097e-01,  -1.54848154e-01,
           1.32753905e-01,  -3.25897955e-02,  -1.21384353e-02,
          -1.79045631e-01,  -3.54186544e-02],
        [ -6.33221153e-02,  -1.65174314e-01,  -7.81467971e-02,
           1.22847882e-01,  -1.27491545e-01,  -3.83513492e-02,
          -1.61563920e-01,  -6.61959264e-02,  -5.61699167e-02,
           3.66758663e-01,   1.25203449e-02,   7.55569430e-02,
           1.05553999e-03,  -9.41494830e-03],
        [  4.44139191e-02,  -2.34477700e-01,  -9.08292091e-02,
           3.00395910e-02,   5.15902738e-02

In [25]:
result[0]['last_states']

LSTMStateTuple(c=array([[ 0.3366676 , -0.29077482, -0.25395624,  0.32299592,  0.46231057,
         0.52961162, -0.07411019,  0.35458935, -0.31239076,  1.04610566,
         0.14380174, -0.03150724,  0.47446598, -0.04275838],
       [ 0.23633369, -0.2899136 , -0.05443759,  0.17035781,  0.04174404,
        -0.09618713,  0.07170209,  0.76536325,  0.09797733,  0.29302954,
        -0.34536875,  0.2033886 , -0.0343691 ,  0.3062763 ],
       [-0.27493965,  0.6201145 ,  0.35372754,  0.03038158,  0.30679997,
        -0.1687715 ,  0.3654092 , -0.77170115, -0.19907563, -0.62141685,
        -0.10491174, -0.0641541 , -0.31151851, -0.43510453]]), h=array([[ 0.14911778, -0.1053815 , -0.13840154,  0.09926418,  0.15416843,
         0.19984677, -0.05633093,  0.23712547, -0.07941336,  0.39303776,
         0.08783498, -0.01623229,  0.16978082, -0.01222476],
       [ 0.0953278 , -0.08127311, -0.02921691,  0.09998805,  0.02798042,
        -0.06453868,  0.02468403,  0.36274521,  0.05616642,  0.18725777,
     

In [26]:
result[0]['last_states'].c

array([[ 0.3366676 , -0.29077482, -0.25395624,  0.32299592,  0.46231057,
         0.52961162, -0.07411019,  0.35458935, -0.31239076,  1.04610566,
         0.14380174, -0.03150724,  0.47446598, -0.04275838],
       [ 0.23633369, -0.2899136 , -0.05443759,  0.17035781,  0.04174404,
        -0.09618713,  0.07170209,  0.76536325,  0.09797733,  0.29302954,
        -0.34536875,  0.2033886 , -0.0343691 ,  0.3062763 ],
       [-0.27493965,  0.6201145 ,  0.35372754,  0.03038158,  0.30679997,
        -0.1687715 ,  0.3654092 , -0.77170115, -0.19907563, -0.62141685,
        -0.10491174, -0.0641541 , -0.31151851, -0.43510453]])

In [27]:
result[0]['last_states'].h

array([[ 0.14911778, -0.1053815 , -0.13840154,  0.09926418,  0.15416843,
         0.19984677, -0.05633093,  0.23712547, -0.07941336,  0.39303776,
         0.08783498, -0.01623229,  0.16978082, -0.01222476],
       [ 0.0953278 , -0.08127311, -0.02921691,  0.09998805,  0.02798042,
        -0.06453868,  0.02468403,  0.36274521,  0.05616642,  0.18725777,
        -0.11655249,  0.05638064, -0.02552506,  0.18477867],
       [-0.08375895,  0.34938533,  0.22601168,  0.0139701 ,  0.14072449,
        -0.10470751,  0.15189855, -0.20326442, -0.12155631, -0.19463379,
        -0.06978402, -0.02532629, -0.15434234, -0.07833108]])